basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        basketsubtotal = basket.get_subtotal_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': basketsubtotal})
        return response

templates/basket/summary.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}
Basket Summary
{%endblock %}
{% block content %}


<main class="pt-5">
    <div class="container" style="max-width: 1000px">
        <div class="col-12">
            <h1 class="h2">Your Cart</h1>
        </div>
        <div class="col-12">
            <p>Manage your <b>items</b> in your cart</p>
        </div>
        <hr />
    </div>


    <div class="container" style="max-width: 1000px">
        <div class="row g-3">
            <div class="col-12 bg-light p-3 d-flex justify-content-between">
                <div class="d-flex d-flex-inline">
                    <div class="pe-3">Order</div>
                </div>


                <div class="text-end">
                    <div class="">Sub Total: <span class="fw-bold">$</span>
                        <div id="subtotal" class="d-inline-flex fw-bold">{{basket.get_subtotal_price}}</div>
                    </div>
                    <div class="pt-2">Total to pay: <span class="fw-bold h5">$</span><span id="total"
                            class="fw-bold h5">{{basket.get_total_price}}</span></div>
                </div>
            </div>


            <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
                <div class="d-grid gap-2 ">
                    <a role="button" href="{% url 'payment:basket' %}" class="btn btn-success fw-bold"
                        type="button">Checkout</a>
                    <button class="btn btn-light" type="button">Save for later</button>
                </div>
            </div>
            <div class="col-md-7 col-lg-8 p-0">

                {% for item in basket %}
                {% with product=item.product %}
                <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
                    <div class="row g-0">
                        <div class="col-md-2 d-none d-md-block">
                            <img class="img-fluid mx-auto d-block" alt="Responsive image"
                                src="{{ product.image.url }}" />
                        </div>
                        <div class="col-md-10 ps-md-3">
                            <div class="card-body p-1">
                                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                                    <p class="card-text pb-3">{{product.title}}</p>
                                </a>
                                <label for="select">License Qty</label>
                                <select id="select{{product.id}}" style="width:50px;height:31px;">
                                    <option value="" selected disabled hidden>{{item.qty}}</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                                <a type="button" id="update-button" data-index="{{product.id}}"
                                    class="update-button text-decoration-none small ps-3">Update</a>
                                <a type="button" id="delete-button" data-index="{{product.id}}"
                                    class="delete-button text-decoration-none small">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endwith %}
                {% endfor %}
            </div>
        </div>

    </div>


{% comment %}
{% for item in basket %} {% with product=item.product %}

<div class="product-item" data-index="asdproduct.idasd" class="mb-4 container">
    <div class="row p-3">
        <div class="col-md-2 p-0">
            <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image"
                src="asd product.image.url asd" />
        </div>

        <div class="col-md-10">
            <a href="asd product.get_absolute_url asd" class="text-decoration-none text-reset fs-6">
                asd product.title asd
            </a>
            <div>
                <div class="col">
                    <div class="row">
                        <div class="col-6">
                        </div>
                        <div class="col-6 text-end">
                            <span class="h6 fw-bold">$asd product.price asd</span>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    <label for="select">Qty</label>
                    <select id="selectasdproduct.idasd">
                        <option selected>asditem.qtyasd</option>
                        <option value="">1</option>
                        <option value="">2</option>
                        <option value="">3</option>
                        <option value="">4</option>
                    </select>
                    <button type="button" id="update-button" data-index="asdproduct.idasd"
                        class="btn btn-outline-secondary btn-sm update-button">
                        Update
                    </button>
                    <button type="button" id="delete-button" data-index="asdproduct.idasd"
                        class="btn btn-outline-secondary btn-sm delete-button">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
    <hr>
</div>
{% endwith %}
{% endfor %}

<div class="col-12 text-end">
    <div class="h6 fw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">asdbasket.get_subtotal_priceasd</div>
    </div>
</div>


<div class="nav left col-12 p-4">
    <div class="title-band title-in-block w-100">
        <h2 class="h5">Basket Summary</h2>
        <hr>
        <dl>
            <dt>Delivery to Continental US <a href="#" class="small text-uppercase text-decoration-none fs12">Change</a>
            </dt>
            <dd><span class="price">$0.00</span></dd>
            <a href="#" class="small text-uppercase text-decoration-none fs12 fw-bold">Show all delivery options</a>
        </dl>
    </div>
    <div class="d-flex justify-content-between w-100">
        <div class="">
            <h2 class="h5">Total <span class="fs-6 fw-normal">(Including TAX)</span></h2>
        </div>
    </div>
</div>
</main> 
{% endcomment %}

<script>
    // Delete Item
    $(document).on("click", ".delete-button", function (e) {
        e.preventDefault();
        var prodid = $(this).data("index");
        $.ajax({
            type: "POST",
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data("index"),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: "post",
            },
            success: function (json) {
                $('.product-item[data-index="' + prodid + '"]').remove();

                if (json.qty == 0) {
                    total = 0
                    subtotal = 0
                }
                else {
                    total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
                    subtotal = json.subtotal
                }

                document.getElementById("subtotal").innerHTML = subtotal;
                document.getElementById("basket-qty").innerHTML = json.qty;
                document.getElementById("total").innerHTML = total;
            },
            error: function (xhr, errmsg, err) { },
        });
    });

    // Update Item
    $(document).on("click", ".update-button", function (e) {
        e.preventDefault();
        var prodid = $(this).data("index");
        $.ajax({
            type: "POST",
            url: '{% url "basket:basket_update" %}',
            data: {
                productid: $(this).data("index"),
                productqty: $("#select" + prodid + " option:selected").text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: "post",
            },
            success: function (json) {

                total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
                document.getElementById("basket-qty").innerHTML = json.qty;
                document.getElementById("subtotal").innerHTML = json.subtotal;
                document.getElementById("total").innerHTML = total;
            },
            error: function (xhr, errmsg, err) { },
        });
    });
</script>
{% endblock %}